apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaMirrorMaker
metadata:
  name: my-mirror-maker
spec:
  version: 2.3.1
  replicas: 1
  consumer:
    bootstrapServers: bootstrap.10.0.0.5.nip.io:443
    groupId: synergy-cloud-mirror-group
    tls:
      trustedCertificates:
        - secretName: synergy-cloud-cluster-ca-cert
          certificate: ca.crt
  producer:
    bootstrapServers: synergy-server-kafka-bootstrap:9093
    tls:
      trustedCertificates:
        - secretName: synergy-server-cluster-ca-cert
          certificate: ca.crt
  whitelist: "^synergy-cloud-.*"
