apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaMirrorMaker
metadata:
  name: my-mirror-maker
spec:
  version: 2.3.1
  replicas: 1
  consumer:
    bootstrapServers: 10.0.0.4:31806
    groupId: synergy-server-mirror-group
  producer:
    bootstrapServers: my-cluster-kafka-bootstrap:9092
  whitelist: "^synergy-server"
