apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaMirrorMaker
metadata:
  name: my-mirror-maker
spec:
  version: 2.3.1
  replicas: 1
  consumer:
    bootstrapServers: 10.0.0.5:32248
    groupId: synergy-cloud-mirror-group
    tls:
      trustedCertificates:
      - secretName: my-cluster-cluster-ca-cert
        certificate: ca.crt
  producer:
    bootstrapServers: my-cluster-kafka-bootstrap:9093
    tls:
      trustedCertificates:
        - secretName: my-cluster-cluster-ca-cert
          certificate: ca.crt
  whitelist: "^synergy-cloud-.*"
