apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: synergy-cloud-local
spec:
  kafka:
    version: 2.3.1
    replicas: 3
    listeners:
      plain: {}
      tls: {}
      external:
        type: ingress
        configuration:
          bootstrap:
            host: bootstrap.192.168.179.76.nip.io
          brokers:
          - broker: 0
            host: broker-0.192.168.179.76.nip.io
          - broker: 1
            host: broker-1.192.168.179.76.nip.io
          - broker: 2
            host: broker-2.192.168.179.76.nip.io
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.3.1"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 2Gi               
        deleteClaim: false
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 1Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}

